/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ToolExperienceFragment = {
    allYearsDataList: (({
        year: number | null;
        awarenessUsageInterestSatisfaction: ({
            awareness: number | null;
            usage: number | null;
            interest: number | null;
            satisfaction: number | null;
        }) | null;
        completion: ({
            total: number | null;
            count: number | null;
            percentage: number | null;
        }) | null;
    }) | null)[] | null;
};
